In [11]:
import numpy as np
L_size=10
weight=1

window_size1=np.c_[np.zeros(L_size) ,weight*np.identity(L_size)[:,:-1] ] + weight*np.identity(L_size) + weight*np.c_[np.identity(L_size)[:,1:], np.zeros(L_size) ]
window_size2=window_size1+np.c_[np.zeros(L_size),np.c_[np.zeros(L_size),np.identity(L_size)[:,:-2]]]
window_size3=window_size2 + np.c_[np.zeros(L_size),np.c_[np.zeros(L_size),np.c_[np.zeros(L_size),np.identity(L_size)[:,:-3]]]]
window_size4=window_size3 + np.c_[np.zeros(L_size),np.c_[np.zeros(L_size),np.c_[np.zeros(L_size),np.c_[np.zeros(L_size),np.identity(L_size)[:,:-4]]]]]

print(window_size2)

[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]
